### ISSUE TITLE
Bug: Not possible to style child element based on toggle state

### ISSUE THREAD

**Issue by bramus** [oddbird/css-toggles#11]
This works:

```css
html {
  toggle-root: checkbox;
}

button {
  toggle-trigger: checkbox;
}

html:toggle(checkbox) {
  background: green; /* ✅ The entire page turns green upon toggling */
}
```

This doesn’t work _([live demo here](https://codepen.io/bramus/pen/dyJaZGp/24b1c529d96f24c62d305014c2a2b78a?editors=1100))_:

```css
html {
  toggle-root: checkbox;
}

button {
  toggle-trigger: checkbox;
}

html:toggle(checkbox) button { /* 👈 Targeting button inside the checkbox-toggled html */
  background: green; /* ❌ Doesn't change to green … */
}
```

A first inspection tells me that the `data-toggle` attribute on the `button` is being altered upon clicking the button, where it should alter the attribute on the `html` element instead.
