### ISSUE TITLE
Support for proposed named-state syntax

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/css-toggles#2]
The current spec doesn't yet support named states, but it will clearly be required for a final toggle feature. In the [explainer](https://css.oddbird.net/toggles/explainer/#toggle-states), I've suggested the following:

- replace* `<initial-state>/<max-state>` syntax with a more clear keyword approach: `<max-state> at <initial-state>`
- replace the current integer `<max-state> ` with a more flexible `<states>`, where: 
   - `<states> = <max-state> | <named-state-list>`
   - `<named-state-list> = '[' <state-name>* ']'` (a bracketed, space-separated list of custom idents)

The resulting syntax would look like this (defining three different toggles):

```css
html {
  toggle-root:
    colors [auto light dark] at light,
    middle-out 10 at 5,
    switch /* `1 at 0` is the default */
  ;
}
```

*for now, we would want to support this in addition to the spec syntax, rather than replacing it…
